### ISSUE TITLE
Near Future Props 0.3.0 release versioning still on 0.2.1

### ISSUE THREAD

**Issue by Serosis** [ChrisAdderley/NearFutureProps#25]
Like the title, the NearFutureProps.version file still represents the last version build number.

Causing Kerbal to spit out that there is an update for it even though it's up-to-date.

**Comment by ChrisAdderley** [comment]
This doesn't appear so to me. Try redownloading?

For example:
https://github.com/ChrisAdderley/NearFutureProps/blob/master/GameData/NearFutureProps/Versioning/NearFutureProps.version#L8
and
<img width="766" alt="screen shot 2018-01-28 at 6 35 58 pm" src="https://user-images.githubusercontent.com/5642064/35491247-20cfffae-045a-11e8-989e-e1eb59b83a6e.png">

**Comment by vrischmann** [comment]
Just downloaded the 0.3.0 release (at [this link](https://github.com/ChrisAdderley/NearFutureProps/archive/0.3.0.zip)) and the version is indeed wrong:

```{
    "NAME":"NearFutureProps",
    "URL":"https://raw.githubusercontent.com/ChrisAdderley/NearFutureProps/master/GameData/NearFutureProps/Versioning/NearFutureProps.version",
    "DOWNLOAD":"http://forum.kerbalspaceprogram.com/index.php?/topic/155465-122-near-future-technologies",
    "VERSION":
    {
        "MAJOR":0,
        "MINOR":2,
        "PATCH":1,
        "BUILD":0
    },
    "KSP_VERSION":
    {
        "MAJOR":1,
        "MINOR":3,
        "PATCH":1
    }
}
```

**Comment by ChrisAdderley** [comment]
I see that you're downloading an outdated archive. Go to the releases page: https://github.com/ChrisAdderley/NearFutureProps/releases
Download the actual item listed on the page from here:
<img width="457" alt="screen shot 2018-02-10 at 9 00 21 pm" src="https://user-images.githubusercontent.com/5642064/36069843-77acd0e0-0ea5-11e8-80e2-bb3e565ee27a.png">
I see that there is a trailing item lower down the page that redirects to the link you posted. The actual release zip for some reason is located at a different address. https://github.com/ChrisAdderley/NearFutureProps/releases/download/0.3.0.1/NearFutureProps0_3_0.zip.
I tried downloading that for you, and I'm really 100% certain it says 0.3.0.
<img width="700" alt="screen shot 2018-02-10 at 9 03 46 pm" src="https://user-images.githubusercontent.com/5642064/36069907-ea166146-0ea5-11e8-96d5-f2a32bbfc227.png">

**Comment by vrischmann** [comment]
Thanks for the explanation !
